//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JimCo.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JimCo.Services.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notice dates are in the past..
        /// </summary>
        internal static string AlertInPast {
            get {
                return ResourceManager.GetString("AlertInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That {0} cannot be deleted because it has associated {1}..
        /// </summary>
        internal static string CantDelete {
            get {
                return ResourceManager.GetString("CantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate {0} with the {1} &apos;{2}&apos;..
        /// </summary>
        internal static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a product from the vendor with id &apos;{0}&apos; with the name &apos;{1}&apos;..
        /// </summary>
        internal static string DuplicateProduct {
            get {
                return ResourceManager.GetString("DuplicateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is invalid..
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model passed is invalid. It is either null, or is missing required information..
        /// </summary>
        internal static string InvalidModel {
            get {
                return ResourceManager.GetString("InvalidModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order passed is invalid. It is either null or is missing required information..
        /// </summary>
        internal static string InvalidOnlineModel {
            get {
                return ResourceManager.GetString("InvalidOnlineModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} with the {1} &apos;{2}&apos; was found..
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice end date is before the start date..
        /// </summary>
        internal static string ReversedDates {
            get {
                return ResourceManager.GetString("ReversedDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That user is already in the group named &apos;{0}&apos;..
        /// </summary>
        internal static string UserAlreadyInGroup {
            get {
                return ResourceManager.GetString("UserAlreadyInGroup", resourceCulture);
            }
        }
    }
}
