//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JimCo.API {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JimCo.API.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts cannot be deleted if they require acknowledgement and have not been acknowledged..
        /// </summary>
        internal static string AckRequired {
            get {
                return ResourceManager.GetString("AckRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert has already been acknowledged in {0}..
        /// </summary>
        internal static string AlertAck {
            get {
                return ResourceManager.GetString("AlertAck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If item is age restricted, then a required age must be specified. Likewise, if an item is not age restricted, it cannot have a required age..
        /// </summary>
        internal static string BadAge {
            get {
                return ResourceManager.GetString("BadAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price in order does not match product price or any current promotion..
        /// </summary>
        internal static string BadPrice {
            get {
                return ResourceManager.GetString("BadPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} cannot be deleted because it has associated {1}..
        /// </summary>
        internal static string CantDelete {
            get {
                return ResourceManager.GetString("CantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot demote the last remaining admin user. There must always be at least one..
        /// </summary>
        internal static string CantDemoteAdmin {
            get {
                return ResourceManager.GetString("CantDemoteAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not enough &apos;{0}&apos; in stock to fulfull this request..
        /// </summary>
        internal static string Insufficient {
            get {
                return ResourceManager.GetString("Insufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is invalid..
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model passed is invalid. It is either null or is missing required information..
        /// </summary>
        internal static string InvalidModel {
            get {
                return ResourceManager.GetString("InvalidModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price for item &apos;{0}&apos; is invalid. It is not the product&apos;s price or the price of one of its promotions..
        /// </summary>
        internal static string InvalidPrice {
            get {
                return ResourceManager.GetString("InvalidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledgement is not required..
        /// </summary>
        internal static string NoAckNeeded {
            get {
                return ResourceManager.GetString("NoAckNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No order can be created. No items were included..
        /// </summary>
        internal static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authenticated, or authentication information is not available..
        /// </summary>
        internal static string NotAuthenticated {
            get {
                return ResourceManager.GetString("NotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to perform that action..
        /// </summary>
        internal static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} with the {1} &apos;{2}&apos; was found..
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The override identifier provided is not a manager..
        /// </summary>
        internal static string NotOverriden {
            get {
                return ResourceManager.GetString("NotOverriden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Product with the {0} &apos;{1}&apos; was found from that vendor..
        /// </summary>
        internal static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is required..
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passed signature does not match the computed signature..
        /// </summary>
        internal static string SignatureMismatch {
            get {
                return ResourceManager.GetString("SignatureMismatch", resourceCulture);
            }
        }
    }
}
